#!/usr/bin/env php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use Aion\Commands\AionSandboxCommand;
use Aion\Commands\AionSparkCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->addCommands([
    new AionSparkCommand(),
    new AionSandboxCommand(),
]);

$application
    ->setDefaultCommand('aion:spark')
    ->run();
